### PR TITLE
efSearch and approximate in Client search

### PR DESCRIPTION
**Pull request by OwenElliottDev**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds the efSearch and approximate into the python client

* **What is the current behavior?** (You can also link to an open issue here)
Currently it is missing despite being part of the 2.0 API

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

### CODE REVIEW

**Review by Mehul-Porwal — DISMISSED** [review]
Can you also bump the version in this file to `3.1.0`? https://github.com/marqo-ai/py-marqo/blob/mainline/setup.py#L21

**Comment by OwenElliottDev** [comment]
@Mehul-Porwal bumped to `3.1.0`

**Review by farshidz — DISMISSED** [review]

**Comment by farshidz** [comment]
Can you please leave the version unchanged so we can release this with other changes?

**Comment by OwenElliottDev** [comment]
Version back to 3.0.1 @farshidz

**Review by farshidz — APPROVED** [review]

**Pull request merged**
